### ISSUE TITLE
[React] Component import CSS

### ISSUE THREAD

**Issue by eksavoy** [electron-userland/electron-forge-templates#32]
Hi,

I have one component (react-calendar-timeline) which importing css directly [Timeline.scss](https://github.com/namespace-ee/react-calendar-timeline/blob/master/src/lib/Timeline.scss).
When I run my app I have an error that I don't know how to solve it :
```
On /Users/romain/Programmation/Humanitech/Lacle/lacle-front/node_modules/react-calendar-timeline/modules/lib/Timeline.css
Uncaught SyntaxError: Unexpected token .
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/romain/Programmation/Humanitech/Lacle/lacle-front/node_modules/electron-compile/lib/require-hook.js:75:14)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/romain/Programmation/Humanitech/Lacle/lacle-front/node_modules/react-calendar-timeline/modules/lib/Timeline.js:19:1)
    at Object.<anonymous> (/Users/romain/Programmation/Humanitech/Lacle/lacle-front/node_modules/react-calendar-timeline/modules/lib/Timeline.js:1074:3)

```

Should I add a configuration in .compilerc? If yes which one ?

Thx
Hope to get help from you

**Comment by anaisbetts** [comment]
This person has hard-coded their component to only support Webpack. Normal node.js modules can only be JavaScript. You should file a bug on this component

**Comment by palavrov** [comment]
Got the same error.
My fix was to use https://github.com/knpwrs/css-modules-electron
