### ISSUE TITLE
Unexpected token: React - Arrow Functions

### ISSUE THREAD

**Issue by S-Mitterlehner** [electron-userland/electron-forge-templates#62]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-forge-templates/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Hello,
i've Created a new Project with electron forge and the react template.

Now I want to use arrow functions, but that won't work.

What can i do?

**Error Message**
```
Uncaught SyntaxError: C:/Users/Test/test/src/app.jsx: Unexpected token (4:20)
    at Parser.pp$5.raise (C:\Users\Test\test\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\Users\Test\test\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$1.parseClassProperty (C:\Users\Test\test\node_modules\babylon\lib\index.js:2571:50)
    at Parser.parseClassProperty (C:\Users\Test\test\node_modules\babylon\lib\index.js:6157:20)
    at Parser.pp$1.parseClassBody (C:\Users\Test\test\node_modules\babylon\lib\index.js:2516:34)
    at Parser.pp$1.parseClass (C:\Users\Test\test\node_modules\babylon\lib\index.js:2406:8)
    at Parser.pp$1.parseExport (C:\Users\Test\test\node_modules\babylon\lib\index.js:2642:19)
    at Parser.parseExport (C:\Users\Test\test\node_modules\babylon\lib\index.js:6000:20)
    at Parser.pp$1.parseStatement (C:\Users\Test\test\node_modules\babylon\lib\index.js:1884:74)
    at Parser.parseStatement (C:\Users\Test\test\node_modules\babylon\lib\index.js:5910:22)
```

**What does your `config.forge` data in `package.json` look like?**

```
{
  "name": "test",
  "productName": "test",
  "version": "1.0.0",
  "description": "My Electron application description",
  "main": "src/index.js",
  "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "lint": "eslint --cache --color --ext .jsx,.js src"
  },
  "keywords": [],
  "author": "---",
  "license": "MIT",
  "config": {
    "forge": {
      "make_targets": {
        "win32": [
          "squirrel"
        ],
        "darwin": [
          "zip"
        ],
        "linux": [
          "deb",
          "rpm"
        ]
      },
      "electronPackagerConfig": {
        "packageManager": "npm"
      },
      "electronWinstallerConfig": {
        "name": "test"
      },
      "electronInstallerDebian": {},
      "electronInstallerRedhat": {},
      "github_repository": {
        "owner": "",
        "name": ""
      },
      "windowsStoreConfig": {
        "packageName": "",
        "name": "test"
      }
    }
  },
  "dependencies": {
    "electron-compile": "^6.4.3",
    "electron-devtools-installer": "^2.2.4",
    "electron-squirrel-startup": "^1.0.0",
    "react": "^15.6.2",
    "react-dom": "^15.6.2",
    "react-hot-loader": "^3.1.3"
  },
  "devDependencies": {
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-es2015-classes": "^6.24.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "electron-forge": "^5.2.2",
    "electron-prebuilt-compile": "3.0.0",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1"
  }
}
```

app.jsx:
```
import React from 'react';

export default class App extends React.Component {
  componentDidMount = () => {
    console.log("test");
  }

  render() {
    return (<div>
      <h2>Welcome to React!</h2>
    </div>);
  }
}
```

**Comment by MarshallOfSound** [comment]
@Imperator145 that isn't just an arrow function, that's known as a class property.

You'll need to enable the class properties plugin for it to work.  https://babeljs.io/docs/en/babel-plugin-transform-class-properties

**Comment by S-Mitterlehner** [comment]
Ok but how to do that? I've added it into the babelrc and the compilerc
.compilerc:
```
{
  "env": {
    "development": {
      "application/javascript": {
        "presets": [
          ["env", { "targets": { "electron": "1.6.0" } }],
          "react"
        ],
        "plugins": ["transform-async-to-generator", "transform-es2015-classes", "react-hot-loader/babel","transform-class-properties"],
        "sourceMaps": "inline"
      }
    },
    "production": {
      "application/javascript": {
        "presets": [
          ["env", { "targets": { "electron": "1.6.0" } }],
          "react"
        ],
        "plugins": ["transform-async-to-generator", "transform-es2015-classes0", "transform-class-properties"],
        "sourceMaps": "none"
      }
    }
  }
}
```

but didn't work for me

**Comment by S-Mitterlehner** [comment]
Ok now i found the problem

Just for reference look here: [https://github.com/babel/babel/issues/4628#issuecomment-250906475](https://github.com/babel/babel/issues/4628#issuecomment-250906475)

**Comment by rsathishtechit** [comment]
@Imperator145 What did you do fix this issue? Can you please post the solution which is worked for you?.
